config/routes.rb
Rails.application.routes.draw do

  devise_for :brands, controllers: {
  sessions:      'brands/sessions',
  passwords:     'brands/passwords',
  registrations: 'brands/registrations'
}
  devise_for :retailers, controllers: {
  sessions:      'retailers/sessions',
  passwords:     'retailers/passwords',
  registrations: 'retailers/registrations'
}

  resources :top, only: [:index]

  resources :contracts, only: [:new, :create, :show, :destroy, :edit]

  resources :retailers, only: [:show, :edit, :update], shallow: true do
    resources :order_fors, only: [:show, :edit, :update, :new, :create, :index]
  end

  resources :brands, only: [:show, :edit, :update], shallow: true do
    resources :registers, only: [:edit, :update, :new, :create, :index, :show]
  end

  resources :contents, only: [:index]
  root to: "contents#index"


end

app/models/brand.rb
class Brand < ActiveRecord::Base
has_many :registers
has_many :products, through: :registers
has_many :contracts
has_many :order_fors

has_many :brand_retailers
has_many :retailers, through: :brand_retailers
has_many :chat_messages, as: :user, dependent: :destroy



devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/brand_retailer.rb
class BrandRetailer < ActiveRecord::Base
  belongs_to :brand
  belongs_to :retailer
  has_many :chat_messages, foreign_key: "group_id"
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :user, polymorphic: true
  belongs_to :brand_retailer
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :products_colors
  has_many :products, through: :products_colors
  has_many :sold_products
  has_many :products

end

app/models/contract.rb
class Contract < ActiveRecord::Base

  belongs_to :brand
  belongs_to :retailer
  belongs_to :product

  has_many :sold_products
  accepts_nested_attributes_for :sold_products, allow_destroy: true, reject_if: :reject_posts

  def reject_posts(attributed)
    attributed['product_id'].blank?
  end

  def total_price
    sold_products.to_a.sum { |sold_product| sold_product.total_price }
  end

end

app/models/order_for.rb
class OrderFor < ActiveRecord::Base
  belongs_to :retailer
  belongs_to :brand

  has_many :sold_products
  has_many :products, through: :sold_products

  accepts_nested_attributes_for :sold_products, allow_destroy: true, reject_if: :reject_posts

  def reject_posts(attributed)
    attributed['product_id'].blank?
  end

  def total_price
    sold_products.to_a.sum { |sold_product| sold_product.total_price }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :register
  belongs_to :size
  belongs_to :color
  belongs_to :brand
  has_many :contracts

  has_attached_file :image,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :image,
                                      content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/products_color.rb
class ProductsColor < ActiveRecord::Base
  belongs_to :color
  belongs_to :product
end

app/models/products_size.rb
class ProductsSize < ActiveRecord::Base
  belongs_to :size
  belongs_to :product
end

app/models/register.rb
class Register < ActiveRecord::Base
  belongs_to :brand
  has_many :products
  accepts_nested_attributes_for :products, allow_destroy: true, reject_if: :reject_posts

 def reject_posts(attributed)
   attributed['style_number'].blank?
 end
end

app/models/retailer.rb
class Retailer < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :order_fors
  has_many :sold_products, through: :order_fors

  has_many :brand_retailers
  has_many :brands, through: :brand_retailers
  has_many :chat_messages, as: :user, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

end

app/models/size.rb
class Size < ActiveRecord::Base

  has_many :products
  has_many :products, through: :products_sizes
  has_many :products_sizes
  has_many :sold_products

end

app/models/sold_product.rb
class SoldProduct < ActiveRecord::Base

  validates :quantity,
             presence: true,
             numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :contract
  belongs_to :product
  belongs_to :color
  belongs_to :size
  belongs_to :retailer

  def total_price
    price * quantity
  end

end

app/controllers/order_fors_controller.rb
class OrderForsController < ApplicationController

  def index
    @orders = OrderFor.all
  end

  def new
    @order = OrderFor.new
    @order.sold_products.build
    @register = Register.find(params[:register_id])
    @products = @register.products
    @retailer = Retailer.find(params[:retailer_id])
    @sizes = Size.all
    @colors = Color.all
  end

  def create
    @order = OrderFor.create(order_params)
    redirect_to order_for_path(@order)
  end

  def show
    @order = OrderFor.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do

      pdf = OrderForPDF.new(@order)

        # 画面にPDFを表示する
        # disposition: "inline" によりPDFはダウンロードではなく画面に表示される
        send_data pdf.render,
          filename:    "#{@order.id}.pdf",
          type:        "application/pdf",
          disposition: "inline"
      end
    end
  end

  def edit
    @order = OrderFor.find(params[:id])
    @products = @order.products
    @sizes = Size.all
    @colors = Color.all
    @retailer = Retailer.find(current_retailer.id)
  end

  def update
    @order = OrderFor.find(params[:id])
    @order.update(order_params)
    redirect_to :root
  end

  private
    def order_params
       params.require(:order_for).permit(sold_products_attributes: [:id, :product_id, :color_id, :size_id, :contract_id, :quantity, :price, :_destroy]).merge(retailer_id:current_retailer.id, brand_id:params[:brand_id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  before_action :move_to_content_page

  def index
    @brands = Brand.all
    @retailers = Retailer.all
  end

  def move_to_content_page
      redirect_to contents_url unless retailer_signed_in? || buyer_signed_in?
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/order_fors_helper.rb
module OrderForsHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/order_fors/_edit_form.html.erb
<div class="container">
  <div class="row">
    <br>
        <%= form_for ( [@order ] ) do |f| %>
          <% @products.each do |product| %>
            <div style="display:inline-flex">
              <%= f.fields_for :sold_products do |builder| %>
                <%= render partial: "sold_product_fields", locals: {product: product, f: builder} %>
              <% end %>
            </div>
            <br>
            <div class="text-right">
              <%= link_to_add_fields "add", f, :sold_products, product %>
            </div>
          <% end %>
            <div class="text-center">
             <%= f.submit "order", class: "btn btn-primary withripple" %>
            </div>
        <% end %>
  </div>
</div>

app/views/order_fors/_form.html.erb
<div class="container">
  <div class="row">
    <br>
    <%= form_for ( [@retailer, @order ] ) do |f| %>
      <% @products.each do |product| %>
        <div style="display:inline-flex">
          <%= f.fields_for :sold_products do |builder| %>
            <%= render partial: "sold_product_fields", locals: {product: product, f: builder} %>
          <% end %>
        </div>
        <br>
          <div class="text-right">
            <%= link_to_add_fields "add", f, :sold_products, product %>
          </div>
      <% end %>
      <div class="text-center">
        <%= f.submit "order", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/order_fors/_sold_product_fields.html.erb
<div class="container">
  <div class="row">
    <br>
    <fieldset>
      <div style="display:inline-flex">
        <tr>
          <%= f.hidden_field :id %>
          <td><%= f.check_box :product_id, {}, "#{product.id}", nil %></td>
          <td><%= product.style_number%></td>
          <td><%= product.size.name%></td>
          <%= f.hidden_field :size_id, :value => product.size_id %>
          <td><%= product.color.name %></td>
          <%= f.hidden_field :color_id, :value => product.color_id %>
          <td><%= product.fabric%></td>
          <td><%= number_to_currency(product.price)%></td>
          <%= f.hidden_field :price, :value => product.price %>
          <td><%= f.number_field(:quantity, min:"0") %></td>
          <td><%= f.hidden_field :_destroy %></td>
          <td><%= link_to "remove", '#', class: "remove_fields" %></td>
          <% unless @order.id.present? %>
          <%= f.hidden_field :retailer, :value => @retailer.id %>
          <% end %>
        </tr>
      </div>
    </fieldset>
  </div>
</div>

app/views/order_fors/edit.html.erb
<%= render 'edit_form'%>

app/views/order_fors/index.html.erb
<section id="portfolio" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">ORDER LIST</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
        </div>
        <%= @orders.each do |order| %>
        <div class="row">
            <div class="col-md-4 col-sm-6 portfolio-item">
                <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <i class="fa fa-plus fa-3x"></i>
                        </div>
                    </div>
                    <img src="<%= asset_path "exhibition.png" %>" class="img-responsive" alt="">
                </a>
                <div class="portfolio-caption">
                    <h4>Brand Name<%= order.brand.company_name %></h4>
                    <p class="text-muted">Graphic Design</p>
                    <% if retailer_signed_in?%>
                    <%= link_to 'Detail', order_for_path(order), {class: 'text-muted' }%>
                    <% else %>
                    <%= link_to 'order', new_brand_order_for_path(register.brand_id), {class: 'btn btn-primary withripple' }%>
                    <% end %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</section>

<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="modal-body">
                        <!-- Project Details Go Here -->
                        <h2>Project Name</h2>
                        <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
                        <img class="img-responsive img-centered" src="img/portfolio/roundicons-free.png" alt="">
                        <div class="row form">
                        <p>
                            <strong>Want these icons in this portfolio item sample?</strong>You can download 60 of them for free, courtesy of <a href="https://getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc">RoundIcons.com</a>, or you can purchase the 1500 icon set <a href="https://getdpd.com/cart/hoplink/18076?referrer=bvbo4kax5k8ogc">here</a>.</p>
                        <ul class="list-inline">
                            <li>Date: July 2014</li>
                            <li>Client: Round Icons</li>
                            <li>Category: Graphic Design</li>
                        </ul>
                        <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close Project</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/order_fors/new.html.erb
<%= render 'form' %>

app/views/order_fors/show.html.erb
<%- model_class = Order -%>
  <div class="page-header">
    <h1>ORDER</h1>
  </div>
    <dl class="dl-horizontal">
      <dt><strong>Order No:</strong></dt>
      <dd><%= @order.id %></dd>
      <dt><strong>Order Date:</strong></dt>
      <dd><%= @order.created_at %></dd>
    </dl>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Style Name</th>
          <th>Size</th>
          <th>Color</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Total Price</th>
        </tr>
      </thead>
      <tbody>
        <% @order.sold_products.each_with_index do |sold_product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= sold_product.product.style_number %></td>
            <td><%= sold_product.color.name %></td>
            <td><%= sold_product.size.name %></td>
            <td><%= sold_product.price %></td>
            <td><%= sold_product.quantity %></td>
            <td><%= number_to_currency sold_product.total_price %></td>
          </tr>
        <% end %>
        <tr class="warning">
          <td colspan="3" />
          <td>Total</td>
          <td><%= number_to_currency @order.total_price %></td>
        </tr>
      </tbody>
    </table>


<%= link_to "edit", edit_order_for_path(@order), :class => 'btn btn-primary' %>

<%= link_to "PDF",
  order_for_path(@order, format: "pdf"),:class => 'btn btn-primary' %>