config/routes.rb
Rails.application.routes.draw do

  devise_for :brands, controllers: {
  sessions:      'brands/sessions',
  passwords:     'brands/passwords',
  registrations: 'brands/registrations'
}
  devise_for :retailers, controllers: {
  sessions:      'retailers/sessions',
  passwords:     'retailers/passwords',
  registrations: 'retailers/registrations'
}

  resources :top, only: [:index]

  resources :contracts, only: [:new, :create, :show, :destroy, :edit]

  resources :retailers, only: [:show, :edit, :update], shallow: true do
    resources :order_fors, only: [:show, :edit, :update, :new, :create, :index]
  end

  resources :brands, only: [:show, :edit, :update], shallow: true do
    resources :registers, only: [:edit, :update, :new, :create, :index, :show]
  end

  resources :contents, only: [:index]
  root to: "contents#index"


end

app/models/retailer.rb
class Retailer < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :order_fors
  has_many :sold_products, through: :order_fors

  has_many :brand_retailers
  has_many :brands, through: :brand_retailers
  has_many :chat_messages, as: :user, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

end

app/controllers/retailers/confirmations_controller.rb
class Retailers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/retailers/omniauth_callbacks_controller.rb
class Retailers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/retailers/passwords_controller.rb
class Retailers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/retailers/registrations_controller.rb
class Retailers::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/retailers/sessions_controller.rb
class Retailers::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/retailers/unlocks_controller.rb
class Retailers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

  def show
    @retailer = Retailer.find(params[:id])
  end

  def edit
  end

  def update
    current_retailer.update(update_params)
  end

  private
  def update_params
    params.require(:retailer).permit(:company_name, :company_address, :country, :user_name, :phone_number, :item_type, :avatar)
  end

end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_retailer.html.erb
<div class="content_post" style="background-image: url(<%= retailer.image.url %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to "detail", brand_products_path(retailer.id), method: :get %>
      </li>
    </ul>
  </div>
  <span class="name">

  </span>
</div>

app/views/retailers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
       <br>
    </div>
    <%= form_for current_retailer do |f| %>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= f.text_field :company_name, placeholder: "company name" %></h3>
          </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "upload image" %> </div>

               <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                        <tr>
                          <td>User Name:</td>
                          <td><%= f.text_field :user_name, placeholder: "user name" %></td>
                        </tr>
                        <tr>
                          <td>Adress</td>
                          <td><%= f.text_field :company_address, placeholder: "company address" %></td>
                        </tr>
                        <tr>
                          <td>Country</td>
                          <td><%= f.text_field :country, placeholder: "country" %></td>
                        </tr>

                        <tr>
                          <td>Phone Number</td>
                          <td><%= f.text_field :phone_number, placeholder: "phone number" %></td>
                        </tr>
                        <tr>
                          <td>Item Type</td>
                          <td><%= f.text_field :item_type, placeholder: "item type" %></td>
                        </tr>
                        <td>Email</td>
                          <td><%= f.email_field :email, placeholder: "email" %></td>
                        </tr>
                    </tbody>
                  </table>
                    <div class="profile_edit">
                      <%= f.submit "send", class: "btn btn-warning btn-ghost" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
  </div>
</div>

app/views/retailers/index.html.erb
<div class="contents row">
  <%= render partial: "retailers/retailer", collection: @products %>

app/views/retailers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
       <br>
    </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @retailer.company_name %></h3>
          </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img src="<%= @retailer.avatar.url(:medium) %>" class="img-circle img-responsive" alt=""> </div>

               <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                        <tr>
                          <td>User Name:</td>
                          <td><%= @retailer.user_name %></td>
                        </tr>
                        <tr>
                          <td>Adress</td>
                          <td><%= @retailer.company_address %></td>
                        </tr>
                        <tr>
                          <td>Country</td>
                          <td><%= @retailer.country %></td>
                        </tr>

                        <tr>
                          <td>Phone Number</td>
                          <td><%= @retailer.phone_number %></td>
                        </tr>
                        <tr>
                          <td>Item Type</td>
                          <td><%= @retailer.item_type %></td>
                        </tr>
                        <tr>
                          <td>Email</td>
                          <td><%= @retailer.email %></td>
                        </tr>
                    </tbody>
                  </table>
                  <% if current_retailer.id == @retailer.id %>
                    <div class="profile_edit">
                      <%= link_to "profile edit", edit_retailer_path(current_retailer), {:class => "btn btn-warning btn-ghost" } %>
                      <%= link_to "see brands", top_index_path, {:class => "btn btn-warning btn-ghost"}%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
  </div>
</div>

app/views/retailers/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>your profile is updated</h3>
    <%= link_to "BACK TO HOME", contents_path %>
  </div>
</div>