config/routes.rb
Rails.application.routes.draw do

  devise_for :brands, controllers: {
  sessions:      'brands/sessions',
  passwords:     'brands/passwords',
  registrations: 'brands/registrations'
}
  devise_for :retailers, controllers: {
  sessions:      'retailers/sessions',
  passwords:     'retailers/passwords',
  registrations: 'retailers/registrations'
}

  resources :top, only: [:index]

  resources :contracts, only: [:new, :create, :show, :destroy, :edit]

  resources :retailers, only: [:show, :edit, :update], shallow: true do
    resources :order_fors, only: [:show, :edit, :update, :new, :create, :index]
  end

  resources :brands, only: [:show, :edit, :update], shallow: true do
    resources :registers, only: [:edit, :update, :new, :create, :index, :show]
  end

  resources :contents, only: [:index]
  root to: "contents#index"


end

app/models/brand.rb
class Brand < ActiveRecord::Base
has_many :registers
has_many :products, through: :registers
has_many :contracts
has_many :order_fors

has_many :brand_retailers
has_many :retailers, through: :brand_retailers
has_many :chat_messages, as: :user, dependent: :destroy



devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/brand_retailer.rb
class BrandRetailer < ActiveRecord::Base
  belongs_to :brand
  belongs_to :retailer
  has_many :chat_messages, foreign_key: "group_id"
end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
  belongs_to :user, polymorphic: true
  belongs_to :brand_retailer
end

app/models/color.rb
class Color < ActiveRecord::Base
  has_many :products_colors
  has_many :products, through: :products_colors
  has_many :sold_products
  has_many :products

end

app/models/contract.rb
class Contract < ActiveRecord::Base

  belongs_to :brand
  belongs_to :retailer
  belongs_to :product

  has_many :sold_products
  accepts_nested_attributes_for :sold_products, allow_destroy: true, reject_if: :reject_posts

  def reject_posts(attributed)
    attributed['product_id'].blank?
  end

  def total_price
    sold_products.to_a.sum { |sold_product| sold_product.total_price }
  end

end

app/models/order_for.rb
class OrderFor < ActiveRecord::Base
  belongs_to :retailer
  belongs_to :brand

  has_many :sold_products
  has_many :products, through: :sold_products

  accepts_nested_attributes_for :sold_products, allow_destroy: true, reject_if: :reject_posts

  def reject_posts(attributed)
    attributed['product_id'].blank?
  end

  def total_price
    sold_products.to_a.sum { |sold_product| sold_product.total_price }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :register
  belongs_to :size
  belongs_to :color
  belongs_to :brand
  has_many :contracts

  has_attached_file :image,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :image,
                                      content_type: ["image/jpg","image/jpeg","image/png"]
end

app/models/products_color.rb
class ProductsColor < ActiveRecord::Base
  belongs_to :color
  belongs_to :product
end

app/models/products_size.rb
class ProductsSize < ActiveRecord::Base
  belongs_to :size
  belongs_to :product
end

app/models/register.rb
class Register < ActiveRecord::Base
  belongs_to :brand
  has_many :products
  accepts_nested_attributes_for :products, allow_destroy: true, reject_if: :reject_posts

 def reject_posts(attributed)
   attributed['style_number'].blank?
 end
end

app/models/retailer.rb
class Retailer < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :order_fors
  has_many :sold_products, through: :order_fors

  has_many :brand_retailers
  has_many :brands, through: :brand_retailers
  has_many :chat_messages, as: :user, dependent: :destroy


  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

end

app/models/size.rb
class Size < ActiveRecord::Base

  has_many :products
  has_many :products, through: :products_sizes
  has_many :products_sizes
  has_many :sold_products

end

app/models/sold_product.rb
class SoldProduct < ActiveRecord::Base

  validates :quantity,
             presence: true,
             numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :contract
  belongs_to :product
  belongs_to :color
  belongs_to :size
  belongs_to :retailer

  def total_price
    price * quantity
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/contract_helper.rb
module ContractHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/common/_header.html.erb
<% if request.path=="/" %>
  <nav class="navbar navbar-default navbar-index navbar-fixed-top header-content">
<% else %>
  <nav class="navbar navbar-default navbar-fixed-top header-content">
<% end %>
<% if brand_signed_in? %>
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand page-scroll" href="/">ORDER</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li><%= link_to "MY PAGE", brand_path(current_brand) %></li>
          <li><%= link_to "Product", brand_registers_path(current_brand) %></li>
          <li><%= link_to "Log out", destroy_brand_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>


<% else %>
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand page-scroll" href="/">ORDER</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <li><%= link_to "Order List", retailer_order_fors_path(current_retailer) %></li>
          <li><%= link_to "Check Brands", top_index_path %></li>
          <li><%= link_to "MY PAGE", retailer_path(current_retailer) %></li>
          <li><%= link_to "Log out", destroy_retailer_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>
</header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Order</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>

<body>

    <% if brand_signed_in?%>
      <% if request.path=="/" %>
        <header class= "nav-index">
      <% else %>
        <header class= "nav">
      <% end %>
          <%= render partial: 'common/header' %>

    <% elsif retailer_signed_in? %>
      <% if request.path=="/" %>
        <header class= "nav-index">
      <% else %>
        <header class= "nav">
      <% end %>
        <%= render partial: 'common/header' %>

    <% else %>
    <% if request.path=="/" %>
      <header class= "nav-index">
    <% else %>
      <header class= "nav">
    <% end %>
      <nav class="navbar navbar-default navbar-index">
        <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
            <% if request.path=="/" %>
              <nav class="navbar navbar-default navbar-index navbar-fixed-top header-content">
            <% else %>
              <nav class="navbar navbar-default navbar-fixed-top header-content">
            <% end %>
              <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                   <a class="navbar-brand page-scroll" href="/">ORDER</a>
                  </div>
<!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                          <li class="hidden">
                            <a href="#page-top"></a>
                          </li>
                          <li>
                            <a class="page-scroll" href="#services">Services</a>
                          </li>
                          <li>
                            <a class="page-scroll" href="#portfolio">Busines Scene</a>
                          </li>
                          <li>
                            <a class="page-scroll" href="#about">About</a>
                          </li>
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                              <ul class="dropdown-menu">
                                <li><%= link_to "Brand", brand_session_path, class: 'post' %></li>
                                <li><%= link_to "Retailer", retailer_session_path, class: 'post' %></li>
                                <li><%= link_to "Brand Register", new_brand_registration_path, class: 'post' %></li>
                                <li><%= link_to "Retailer Register", new_retailer_registration_path, class: 'post' %></li>
                              </ul>
                          </li>
                        </ul>
                    </div>
              </div>
          </nav>

        </div>
        </div><!-- /.container-fluid -->
     </nav>

  <% end %>

</header>

<%= yield %>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright &copy; ORDER 2016</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li><a href="#">Privacy Policy</a>
                    </li>
                    <li><a href="#">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

</body>

</html>